on:
  - push

jobs:
  terraform-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v1
      - name: set Terraform
        uses: hasicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: terraform init
        run: terraform init
      - name: terraform validate
        run: terraform validate
      - name: Multi line string
        run: |
          pwd
          ls -a
